# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.2.2"
slug: example
description: Example add-on
url: "https://github.com/Visolo/ha-addons/tree/main/example"
codenotary: pose_b@hotmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/Visolo/{arch}-addon-example"
