name: Custom deps deployment Visolo
init: false
version: 1.3.5
slug: custom_deps
description: Manage custom Python modules in Home Assistant deps
url: https://github.com/Visolo/ha-addons/tree/main/custom_deps
codenotary: pose_b@hotmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: once
advanced: true
homeassistant: 2021.7.0
boot: manual
map:
  - config:rw
options:
  pypi: 
    -
  apk: []
schema:
  pypi:
    - str
  apk:
    - str
image: ghcr.io/visolo/{arch}-addon-custom_deps
