# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
# build_from:
#   aarch64: "ghcr.io/home-assistant/aarch64-base:3.14"
#   amd64: "ghcr.io/home-assistant/amd64-base:3.14"
#   armhf: "ghcr.io/home-assistant/armhf-base:3.14"
#   armv7: "ghcr.io/home-assistant/armv7-base:3.14"
#   i386: "ghcr.io/home-assistant/i386-base:3.14"
build_from:
  amd64: ghcr.io/home-assistant/amd64-base-python:3.10-alpine3.16
  i386: ghcr.io/home-assistant/i386-base-python:3.10-alpine3.16
  armhf: ghcr.io/home-assistant/armhf-base-python:3.10-alpine3.16
  armv7: ghcr.io/home-assistant/armv7-base-python:3.10-alpine3.16
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.10-alpine3.16
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: UPS Pico"
  org.opencontainers.image.description: "Enable daemon for UPS Pico notifications and system shutdown."
  org.opencontainers.image.source: "https://github.com/home-assistant/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
  CLI_VERSION: 4.21.0
