# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: UPS Pico HV3.0 FSSD
version: "1.0.0"
slug: ups_pico_hv30
description: Enable daemon for UPS Pico HV3.0A/B/B+ notifications and system shutdown
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
#  - amd64
#  - i386
init: false
# For HA CLI
hassio_api: true
hassio_role: manager
# Map config folder
map:
  - config:rw
# Permissions
gpio: true
# privileged:
#   - SYS_RAWIO
#   - SYS_ADMIN
#   - SYS_MODULE
devices:
  - /dev/mem
  - /dev/gpiomem
#kernel_modules: true
#apparmor: false
#full_access: true
options:
  identifying_name: "Home Assistant"
  log_level: "info"
  test_mode: True
  mail_enabled: False
  mail_username: ""
  mail_sender-email-address: ""
  mail_sender-password: ""
  mail_recipient-email-address: ""
  mail_subject-template: "emailAlertSubject.template"
  mail_body-template: "emailAlertBody.template"
  mail_server: ""
  mail_security: ""
  mail_port: "25"
schema:
  identifying_name: "str"
  log_level: list(info|debug)
  test_mode: bool
  mail_enabled: bool
  mail_username: "str?"
  mail_sender-email-address: "str?"
  mail_sender-password: "password?"
  mail_recipient-email-address: "str?"
  mail_subject-template: "str?"
  mail_body-template: "str?"
  mail_server: "str?"
  mail_security: "str?"
  mail_port: "port?"
#image: "ghcr.io/home-assistant/{arch}-addon-example"
